title: "Biel Rosales | Especialista OSINT & Ciberseguridad"
description: "Portafolio profesional de investigación OSINT, geolocalización avanzada y análisis de ciberseguridad por Biel Rosales."
author: "Biel Rosales"
email: "rosalesmartinezbiel2@gmail.com"
linkedin_username: "biel-rosales-2a488220b"
github_username: "kbbaa"
twitter_username: "" # Opcional
baseurl: ""
url: "https://kbbaa.github.io"

markdown: kramdown
permalink: pretty
theme: null
layouts_dir: _layouts

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _layouts
  - assets
